---
image: ruby:2.6

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

shortlinks:test:
  stage: test
  image:
    registry.gitlab.fachschaften.org/tudo-fsinfo/admin/gitlab-pages-shortlinks:latest
  script: shortlinks generate -c vanitymap.txt
  except:
    - main

test:
  stage: test
  dependencies:
    - shortlinks:test
  before_script:
    - bundle install
  script:
    - bundle exec jekyll build -d test
  except:
    - main

shortlinks:generate:
  stage: build
  image:
    registry.gitlab.fachschaften.org/tudo-fsinfo/admin/gitlab-pages-shortlinks:latest
  script: shortlinks generate vanitymap.txt
  artifacts:
    expire_in: 1h
    paths:
      - public
  only:
    - main

pages:
  stage: deploy
  dependencies:
    - shortlinks:generate
  before_script:
    - bundle install
  script:
    - bundle exec jekyll build -d public
  artifacts:
    expire_in: 1h
    paths:
      - public
  only:
    - main
