title: Konferenz der Informatikfachschaften
lang: de
description: 'Die Konferenz der Informatikfachschaften (KIF) ist ein halbjährlich stattfindendes Treffen von Studierenden des Fachbereichs Informatik.'
sass:
    style: compressed
